### ISSUE TITLE
小程序 getPhoneNumber 能测试一下吗？

### ISSUE THREAD

**Issue by aehyok** [Yill625/taro3-vue3-template#1]
`  <nut-button
    type="primary"
    @click="clickPhoneNumber"
    open-type="getPhoneNumber"
    @getphonenumber="getPhoneNumber"
    >获取手机号</nut-button
  >
  const clickPhoneNumber = () => {
    console.log('clickPhoneNumber')
  }
  const getPhoneNumber = (e) => {
    console.log('ee', 'bb')
    console.log(e.detail.errMsg)
    console.log(e.detail.iv)
    console.log(e.detail.encryptedData)
  }
`

click事件可以调用，wx.login也调用了的，获取手机号的console就是不执行

**Comment by Yill625** [comment]
看了下这个是要放在原生的组件按钮上才能生效 
所以是NutUi这个组件按钮不支持 
![image](https://user-images.githubusercontent.com/25902472/144420647-f6e5de62-a56d-4983-8ff3-422f2a634abe.png)

**Comment by Yill625** [comment]
```html
<button open-type="getPhoneNumber" @getphonenumber="getPhoneNumber">小型按钮</button>
```
还是用小程序自带的按钮组件 然后直接自己写个样式就好了

**Comment by aehyok** [comment]
哇撒，非常感谢

**Comment by aehyok** [comment]
果然nutui的按钮是不行的
